version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: car-value-db
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: pass123
